//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoMyData.proto
namespace ProtoMyData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MyData")]
  public partial class MyData : global::ProtoBuf.IExtensible
  {
    public MyData() {}
    

    private string _resume = @"I'm goodman";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"resume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"I'm goodman")]
    public string resume
    {
      get { return _resume; }
      set { _resume = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}